### ISSUE TITLE
Blank Screen on Watch Simulator

### ISSUE THREAD

**Issue by dancinllama** [developerforce/SalesforceWear-DevPack-For-AppleWatch#2]
I've built and started the simulator for the Salesforce Watch app.  Opened the 42mm watch simulator.  Logged into my developer org that has two pending approvals (goes to a blue "Apple Watch Example" screen and stays there).  Stopped the simulator then start the Salesforce Watchkit App Simulator.  When I open the Salesforce Watch application on the iphone sim, the apple watch simulator shows a spinning progress bar for a bit, stops, and then shows a blank screen with only the time. 

I don't see the approval glance or anything.  I'm not seeing anything in the xcode debug console.  I don't see any transactions in my Salesforce debug logs for my developer org user either.  I ran the query in the approvals example in workbench, and that does return 2 results.  

Any idea why I'm still seeing a blank screen, or where I should look for a possible exception?  Below is a screenshot of what my simulator looks like.  Thanks.

![screen shot 2015-03-31 at 11 04 45 am](https://cloud.githubusercontent.com/assets/796422/6923187/c9761520-d795-11e4-8541-38d1ddddbd0f.gif)

**Comment by quintonwall** [comment]
Do you see any debug in the console about number of rows returned? I'm assuming you have approvals in your org?

**Comment by dancinllama** [comment]
Ah your tutorial on the main page mentions running the Salesforce Watch app, but not the Salesforce Watch Glance app as the target.  It took a little bit of tinkering, but after I ran the glance target and restarted the Salesforce Watch app in the simulator, I got the approvals screen to show.  Thanks for your help.
