### ISSUE TITLE
Salesforce Authentication Problem

### ISSUE THREAD

**Issue by BrennonTWilliams** [developerforce/SalesforceWear-DevPack-For-AppleWatch#3]
I downloaded the source for this project, and am running it in Xcode 6.4 with simulator target set to the iPhone 6 v8.2 as the Readme recommended. I run SalesforceWatch and log in successfully, then I switch targets to SalesforceWatch WatchKit App and run it again. The Apple Watch simulator stays black and the iPhone simulator stays on the page "Salesforce: Apple Watch Sample".

I get this warning:

    warning: Capabilities that require entitlements from "SalesforceWatch WatchKit Extension/SalesforceWatch WatchKit Extension.entitlements" may not function in the Simulator because no valid signing identities (i.e. certificate and private key pair) matching the team ID “4X564CR95Y” were found.

So presumably the issue is with Salesforce authentication. Any thoughts as to what I could be doing wrong here?

**Comment by ankushdureja** [comment]
Hi,

I am facing the same issue. When I try to use SalesforceWatch Glance app then nothing is happening after initial screen. See Screenshot below:
![watch glance](https://cloud.githubusercontent.com/assets/13194433/8517388/ffacbb5a-23dd-11e5-8123-1fb610caf717.JPG)

When I try to use SalesforceWatch Watchkit app , then I am getting this in simulator
![salesforcewatch watchkit app](https://cloud.githubusercontent.com/assets/13194433/8517453/ba79336e-23de-11e5-9f1e-f8bcb31cffd6.JPG)


Please help.

**Comment by ankushdureja** [comment]
Also I should mention one thing that when I try to switch then I get this message and I clicked on Stop button
![applewatch switch](https://cloud.githubusercontent.com/assets/13194433/8518136/f6c51e90-23e4-11e5-8f4b-f8d5d2c8fafa.JPG)

**Comment by ankushdureja** [comment]
@BrennonTWilliams Were you able to resolve this issue?
