### ISSUE TITLE
Approvals app not showing

### ISSUE THREAD

**Issue by ankushdureja** [developerforce/SalesforceWear-DevPack-For-AppleWatch#4]
I am using latest Xcode from App store. I opened project using Xcode, then I selected SalesforceWatch and run the app. I did login and got this output:

![salesforce watch](https://cloud.githubusercontent.com/assets/13194433/8518204/8bd3eb60-23e5-11e5-8d1c-09e56a1f0ce0.JPG)

After that I tried to switch target to 'SalesforceWatch WatchKit App' and 'SalesforceWatch Glance App'. After running with new target I got this message:

![applewatch switch](https://cloud.githubusercontent.com/assets/13194433/8518248/e5c9b636-23e5-11e5-8250-59c6d97b37fb.JPG)

I clicked on stop button then I got this screen when I used 'SalesforceWatch WatchKit App' target

![salesforcewatch watchkit app](https://cloud.githubusercontent.com/assets/13194433/8518277/2371c6c2-23e6-11e5-9526-d26f4a571a50.JPG)

and I got this screen when used 'SalesforceWatch Glance App' target:

![watch glance](https://cloud.githubusercontent.com/assets/13194433/8518310/68e244f2-23e6-11e5-864f-cd1ef75c7c69.JPG)

After that nothing happened. Please let me know if I am doing something wrong.

Thanks
Ankush

**Comment by ankushdureja** [comment]
@quintonwall

**Comment by quintonwall** [comment]
It's a timing issue. You need to make sure that the iPhone app is started before the watch interface loads. (note: watchOS2 makes this, and app dev much better. I already have an updated app and am rolling it into the v2 of the wear dev pack

**Comment by ankushdureja** [comment]
@quintonwall How we can make sure that iPhone app is started before the watch interface loads.
