### ISSUE TITLE
xcode 7 - beta 3 - won't compile 'libSalesforceNetworkSDK.a(SFNetworkEngine.o)' does not contain bitcode

### ISSUE THREAD

**Issue by johndpope** [developerforce/SalesforceWear-DevPack-For-AppleWatch#5]
![screen shot 2015-07-09 at 4 33 47 pm](https://cloud.githubusercontent.com/assets/289994/8589330/62ccb9ca-2658-11e5-8fcf-cc3716b2ffbe.png)

**Comment by quintonwall** [comment]
Mobile sdk prior to v4 was not bitcode enabled. V4+ resolves this. The version2 branch of the devpack uses mobile sdk 4.0
